version: "3.1"

services:
  singlelink-api:
    image: neutroncreative/singlelink-api-enterprise:latest
    build:
      context: api
      dockerfile: api.Dockerfile
    env_file:
      - api-config.env
    ports:
      - "80:80"
    networks:
      - singlelink

  singlelink-editor:
    image: neutroncreative/singlelink-editor-enterprise:latest
    build:
      context: editor
      dockerfile: editor.Dockerfile
    depends_on:
      - singlelink-api
    env_file:
      - editor-config.env
    ports:
      - "3333:80"
    networks:
      - singlelink

  singlelink-renderer:
    image: neutroncreative/singlelink-renderer-enterprise:latest
    build:
      context: renderer
      dockerfile: renderer.Dockerfile
    depends_on:
      - singlelink-api
    env_file:
      - renderer-config.env
    ports:
      - "3000:80"
    networks:
      - singlelink

networks:
  singlelink:
